name: C/C++ Building CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Ninja
      uses: ashutoshvarma/setup-ninja@v1.1

    - name: configure
      run: cmake --workflow --preset default
